import { test, expect, type Page } from '@playwright/test'
import { readFileSync } from 'node:fs'
const script = readFileSync('dist/tempo.user.js','utf8')
const html = readFileSync('e2e/jira.html','utf8')
async function launch(page: Page, setup = false) {
  await page.route('https://demo.atlassian.net/**', route => route.fulfill({ contentType:'text/html', body: html }))
  await page.addInitScript({ path:'e2e/fixture.js' })
  await page.goto(`https://demo.atlassian.net/browse/NOVA-318${setup ? '?setup' : ''}`)
  await page.addScriptTag({ content:script })
  await page.getByRole('button',{name:'Open Tempo'}).click()
  if (!setup) {
    await expect(page.getByRole('status')).toContainText('Worklogs refreshed')
    await page.getByRole('textbox',{name:'Worklog date'}).fill('2026-09-19')
    await page.getByRole('button',{name:'Refresh',exact:true}).click()
    await expect(page.getByRole('button',{name:'Refresh',exact:true})).toBeEnabled()
    await expect(page.getByRole('link',{name:'NOVA-318',exact:true})).toBeVisible()
  }
}
test('connect discovers account ID, retains tokens privately and can disconnect', async ({page}) => {
  await launch(page,true)
  await page.getByLabel('Jira email',{exact:true}).fill('demo@example.com')
  await page.getByLabel('Jira API token',{exact:true}).fill('demo-jira-token')
  await page.getByLabel('Tempo API token',{exact:true}).fill('demo-tempo-token')
  await page.getByRole('button',{name:'Connect accounts'}).click()
  await expect(page.getByRole('status')).toContainText('Connected as Alex Morgan')
  await expect(page.getByLabel('Jira API token',{exact:true})).toHaveValue('')
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('fixture-state')!).credentials.accountId)).toBe('demo-account')
  page.once('dialog',d => d.accept())
  await page.getByRole('button',{name:'Remove credentials'}).click()
  await expect(page.getByRole('status')).toContainText('Credentials removed')
})
test('creates interval worklog, shows details and deletes selection',async ({page}) => {
  const errors: string[]=[]; page.on('pageerror',e=>errors.push(e.message))
  await launch(page)
  if (process.env.TEMPO_QA_DIR) await page.screenshot({path:`${process.env.TEMPO_QA_DIR}/desktop.png`})
  await page.getByLabel('Issue or alias',{exact:true}).fill('review')
  await page.getByLabel('Duration or interval',{exact:true}).fill('14:00-14:35')
  await page.getByLabel('Description',{exact:true}).fill('<script>alert(1)</script>')
  await page.getByLabel('Remaining estimate (optional)',{exact:true}).fill('0h')
  await page.getByRole('button',{name:'Save worklog'}).click()
  await expect(page.getByRole('status')).toContainText('Saved 35m to NOVA-318')
  await page.getByLabel('Show descriptions & worklog IDs').check()
  await expect(page.getByText('<script>alert(1)</script>',{exact:true})).toBeVisible()
  await page.getByLabel('Select worklog 931842').check()
  page.once('dialog',d=>d.accept())
  await page.getByRole('button',{name:'Delete selected'}).click()
  await expect(page.getByRole('status')).toContainText('Deleted 1 worklog')
  await expect(page.getByLabel('Select worklog 931842')).toHaveCount(0)
  expect(errors).toEqual([])
})
test('aliases survive reload and map to canonical issue keys',async ({page}) => {
  await launch(page)
  await page.getByRole('tab',{name:'Aliases',exact:true}).click()
  await page.getByLabel('Alias',{exact:true}).fill('triage')
  await page.getByLabel('Issue key',{exact:true}).fill('ops-42')
  await page.getByRole('button',{name:'Save alias'}).click()
  await expect(page.getByRole('cell',{name:'triage',exact:true})).toBeVisible()
  await page.reload(); await page.addScriptTag({content:script})
  await page.getByRole('button',{name:'Open Tempo'}).click()
  await expect(page.getByRole('status')).toContainText('Worklogs refreshed')
  await page.getByRole('tab',{name:'Aliases',exact:true}).click()
  await expect(page.getByRole('cell',{name:'OPS-42',exact:true})).toBeVisible()
})
test('tracker pauses, resumes, keeps failed intervals and retries only retained work',async ({page}) => {
  await launch(page)
  await page.getByRole('tab',{name:'Trackers',exact:true}).click()
  await page.getByLabel('Issue or alias',{exact:true}).fill('NOVA-318')
  await page.getByRole('button',{name:'Start tracker'}).click()
  await expect(page.getByText('Running',{exact:true})).toBeVisible()
  await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('fixture-state')!);s.trackers['NOVA-318'].activeSince-=120000;localStorage.setItem('fixture-state',JSON.stringify(s))})
  await page.getByRole('button',{name:'Pause',exact:true}).click()
  await expect(page.getByText('Paused',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Resume',exact:true}).click()
  await expect(page.getByText('Running',{exact:true})).toBeVisible()
  await page.evaluate(()=>{(window as any).__failPosts=true})
  await page.getByRole('button',{name:'Stop & log'}).click()
  await expect(page.getByRole('status')).toContainText('failed and remain paused')
  await expect(page.getByRole('button',{name:'Stop & log'})).toBeVisible()
  await page.evaluate(()=>{(window as any).__failPosts=false})
  await page.getByRole('button',{name:'Stop & log'}).click()
  await expect(page.getByRole('status')).toContainText('Logged all intervals')
  await expect(page.getByText('No trackers yet.')).toBeVisible()
})
test('invalid input never creates a worklog and mobile panel fits',async ({page}) => {
  await page.setViewportSize({width:390,height:844})
  await launch(page)
  await page.getByLabel('Duration or interval',{exact:true}).fill('0h')
  if (process.env.TEMPO_QA_DIR) await page.screenshot({path:`${process.env.TEMPO_QA_DIR}/mobile.png`})
  await page.getByRole('button',{name:'Save worklog'}).click()
  await expect(page.locator('.status.error')).toBeVisible()
  const count = await page.evaluate(()=>(window as any).__requests.filter((r:any)=>r.method==='POST').length)
  expect(count).toBe(0)
  const box = await page.getByRole('region',{name:'Tempo panel'}).boundingBox()
  expect(box?.width).toBeLessThanOrEqual(390)
  await page.getByRole('button',{name:'Close Tempo'}).click()
  await expect(page.getByRole('button',{name:'Open Tempo'})).toBeVisible()
})

test('two tabs cannot upload the same tracker interval twice',async ({page,context}) => {
  await launch(page)
  await page.evaluate(()=>{
    const state=(window as any).GM_getValue('ignored',{})
    state.trackers['NOVA-318']={issueKey:'NOVA-318',description:'Concurrent stop',activeSince:null,intervals:[{id:'only-interval',start:Date.now()-180000,end:Date.now()-60000}]}
    localStorage.setItem('fixture-state',JSON.stringify(state))
  })
  await page.getByRole('tab',{name:'Trackers',exact:true}).click()
  const second=await context.newPage()
  await launch(second)
  await second.getByRole('tab',{name:'Trackers',exact:true}).click()
  await Promise.all([page.getByRole('button',{name:'Stop & log'}).click(),second.getByRole('button',{name:'Stop & log'}).click()])
  await expect.poll(async()=>page.evaluate(()=>Object.keys(JSON.parse(localStorage.getItem('fixture-state')!).trackers).length)).toBe(0)
  const total=(await page.evaluate(()=>(window as any).__requests.filter((r:any)=>r.method==='POST').length))+(await second.evaluate(()=>(window as any).__requests.filter((r:any)=>r.method==='POST').length))
  expect(total).toBe(1)
})

test('batch deletion keeps failed IDs and still attempts the next item',async ({page}) => {
  await launch(page)
  await page.evaluate(()=>{(window as any).__deleteFailId='931842'})
  await page.getByLabel('Select worklog 931842').check()
  await page.getByLabel('Select worklog 931859').check()
  page.once('dialog',d=>d.accept())
  await page.getByRole('button',{name:'Delete selected'}).click()
  await expect(page.getByRole('status')).toContainText('Could not delete: 931842')
  await expect(page.getByLabel('Select worklog 931842')).toBeVisible()
  await expect(page.getByLabel('Select worklog 931859')).toHaveCount(0)
})
